version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules 
        ports:
            - "5001:5001"
        env_file:
            - ./backend/.env
        depends_on:
            - mongodb
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/usr/src/app
        ports:
            - "8080:80"
        networks:
            - app-network

    mongodb:
        image: mongo:4.4-bionic
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
            - mongo_data:/data/db
        ports:
            - "27017:27017"
        networks:
            - app-network

volumes:
    mongo_data:

networks:
    app-network:
